# Site settings
title: Fatal Extraction
sub_title: The Human Cost of Australia's Mining Empire in Africa

description: > # this means to ignore newlines until "baseurl:"
  Fatal Extraction is an international collaboration combining corporate data and extensive field reporting to reveal deaths, injuries and community conflicts linked to Australian mining companies across Africa. Australia has more mining companies in Africa than other mining giants such as Canada and China.

baseurl: "" # the subpath of your site, e.g. /blog/
url: https://fatalextraction.investigativecenters.org
enforce_ssl: fatalextraction.investigativecenters.org

twitter_username: AfricanCIR
github_username:  ANCIR
email:            info@investigativecentres.org

google_analytics: UA-63787251-3

# Build settings
markdown: kramdown
